backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

site_url: "https://gregarious-marshmallow-6ef817.netlify.app"

collections:
  - name: "status"
    label: "CP 운영 현황"
    files:
      - file: "content/status/index.json"
        label: "운영 현황 목록"
        name: "status_list"
        fields:
          - label: "운영 현황 목록"
            name: "items"
            widget: "list"
            fields:
              - { label: "제목", name: "title", widget: "string" }
              - { label: "날짜", name: "date", widget: "string" }
              - { label: "구분", name: "category", widget: "string" }
              - { label: "요약", name: "summary", widget: "text" }
              - { label: "링크", name: "link", widget: "string", required: false }

  - name: "library"
    label: "CP 자료실"
    files:
      - file: "content/library/index.json"
        label: "자료실 목록"
        name: "library_list"
        fields:
          - label: "자료 목록"
            name: "items"
            widget: "list"
            fields:
              - { label: "자료명", name: "title", widget: "string" }
              - { label: "설명", name: "description", widget: "string" }
              - { label: "날짜", name: "date", widget: "string" }
              - { label: "링크", name: "link", widget: "string" }
